% --- Funktion zum Hinzufuegen der Buttons (bleibt auch generisch) ---
function addPlaybackControls(f, play_data)
    if isempty(getappdata(f, 'PlaybackData'))
        setappdata(f, 'PlaybackData', play_data);
    end
    
    p = uipanel(f, 'Title', 'Wiedergabesteuerung', ...
        'Units', 'normalized', 'Position', [0.7 0.93 0.28 0.06]);
    
    uicontrol(p, 'Style', 'pushbutton', 'String', '▶️ Start', ...
        'Units', 'normalized', 'Position', [0.05 0.1 0.3 0.7], ...
        'Callback', {@play_callback, f});
    
    uicontrol(p, 'Style', 'pushbutton', 'String', '⏸️ Anhalten', ...
        'Units', 'normalized', 'Position', [0.35 0.1 0.3 0.7], ...
        'Callback', {@pause_callback, f});

    uicontrol(p, 'Style', 'pushbutton', 'String', '⏪ Zurück', ...
        'Units', 'normalized', 'Position', [0.65 0.1 0.3 0.7], ...
        'Callback', {@rewind_callback, f});
end