function btn_snap = erstelle_top_bar(fig, meta, datei_pfad_voll, signale, cfg)
% Erstellt die obere Info-Leiste
% Autor: [Benutzer]
% Datum: 2026-06-24

C = cfg.farben;
topbar = uipanel(fig, 'Position', [0, cfg.fenster.hoehe_px - cfg.layout.topbar_hoehe, cfg.fenster.breite_px, cfg.layout.topbar_hoehe], ...
    'BackgroundColor', C.topbar, 'BorderType', 'none');

uilabel(topbar, 'Position', [10, 10, 200, 25], ...
    'Text', sprintf('%s  |  %s', meta.fahrzeug, meta.event), ...
    'FontSize', 13, 'FontWeight', 'bold', ...
    'FontColor', C.weiss, 'BackgroundColor', 'none');

uilabel(topbar, 'Position', [230, 10, 200, 25], ...
    'Text', sprintf('%s  %s', meta.datum, meta.zeit), ...
    'FontSize', 11, 'FontColor', C.grau, 'BackgroundColor', 'none');

[~, fn, ext] = fileparts(datei_pfad_voll);
uilabel(topbar, 'Position', [430, 10, 380, 25], ...
    'Text', [fn, ext], 'FontSize', 10, 'FontColor', C.grau2, 'BackgroundColor', 'none');

uilabel(topbar, 'Position', [845, 13, 85, 18], ...
    'Text', 'Snapshot (s):', 'FontSize', 9, ...
    'FontColor', C.grau, 'BackgroundColor', 'none');

ef_snap = uieditfield(topbar, 'numeric', ...
    'Position', [935, 11, 75, 23], 'Value', 0, ...
    'FontSize', 9, 'BackgroundColor', C.karte, 'FontColor', C.weiss);

btn_snap = uibutton(topbar, 'Position', [1020, 8, 115, 28], ...
    'Text', '▶  Snapshot', ...
    'BackgroundColor', C.rot, 'FontColor', C.weiss, 'FontWeight', 'bold');

btn_snap.UserData = ef_snap;

uibutton(topbar, 'Position', [1150, 8, 130, 28], ...
    'Text', 'Export PDF / PNG', ...
    'BackgroundColor', [0.25, 0.25, 0.25], ...
    'FontColor', C.weiss, 'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(~,~) io.export_report(signale, meta, cfg));
end