function [ef_start, sl_start, ef_ende, sl_ende, lbl_bereich] = erstelle_slider_panel(fig, cfg, t_gesamt)
% Erstellt Zeitfenster-Slider
% Autor: [Benutzer]
% Datum: 2026-06-24

C = cfg.farben;
y_pos = cfg.fenster.hoehe_px - cfg.layout.topbar_hoehe - cfg.layout.slider_hoehe;
slider_panel = uipanel(fig, 'Position', [0, y_pos, cfg.fenster.breite_px, cfg.layout.slider_hoehe], ...
    'BackgroundColor', C.slider_hintergrund, 'BorderType', 'none');

uilabel(slider_panel, 'Position', [8, 17, 55, 18], ...
    'Text', 't start (s)', 'FontSize', 9, 'FontColor', C.rot, 'BackgroundColor', 'none');
ef_start = uieditfield(slider_panel, 'numeric', ...
    'Position', [68, 15, 65, 22], 'Value', 0, 'Limits', [0, t_gesamt], ...
    'FontSize', 9, 'BackgroundColor', C.karte, 'FontColor', C.weiss);
sl_start = uislider(slider_panel, 'Position', [145, 28, 550, 3], ...
    'Limits', [0, t_gesamt], 'Value', 0, 'MajorTicks', [], 'MinorTicks', []);

uilabel(slider_panel, 'Position', [720, 17, 55, 18], ...
    'Text', 't end (s)', 'FontSize', 9, 'FontColor', C.rot, 'BackgroundColor', 'none');
ef_ende = uieditfield(slider_panel, 'numeric', ...
    'Position', [780, 15, 65, 22], 'Value', t_gesamt, 'Limits', [0, t_gesamt], ...
    'FontSize', 9, 'BackgroundColor', C.karte, 'FontColor', C.weiss);
sl_ende = uislider(slider_panel, 'Position', [858, 28, 550, 3], ...
    'Limits', [0, t_gesamt], 'Value', t_gesamt, 'MajorTicks', [], 'MinorTicks', []);

lbl_bereich = uilabel(slider_panel, 'Position', [1430, 17, 160, 18], ...
    'Text', sprintf('%.0f s total', t_gesamt), ...
    'FontSize', 9, 'FontColor', C.grau, 'BackgroundColor', 'none');
end