function signale_liste = get_signal_liste(cfg)
    % Zentrale Liste aller zu extrahierenden Signale
    % Autor: [Benutzer]
    % Datum: 2026-06-24
    % Changelog: INS_vel_x/y hinzugefuegt fuer GPS Dead-Reckoning

    signale_liste = {
        'speed_can', 'steering_wheel_angle_can', 'steering_wheel_angle_e_b_can', ...
        'brake_pressed_b_can', 'brake_balance_front_can', ...
        'pbrake_front_can', 'pbrake_rear_can', 'pbrake_front_e_b_can', 'pbrake_rear_e_b_can', ...
        'pbrake_front_raw_can', 'pbrake_rear_raw_can', ...
        'apps1_can', 'apps2_can', 'apps3_can', 'apps_res_can', 'apps_state_can', ...
        'apps1_e_b_can', 'apps2_e_b_can', 'apps3_e_b_can', 'apps_bse_impl_b_can', ...
        'rocker_fl_can', 'rocker_fr_can', 'rocker_rl_can', 'rocker_rr_can', ...
        'rocker_fl_e_b_can', 'rocker_fr_e_b_can', 'rocker_rl_e_b_can', 'rocker_rr_e_b_can', ...
        'INS_acc_x_can', 'INS_acc_y_can', 'INS_acc_z_can', ...
        'INS_ang_vel_z_can', 'INS_vel_x_can', 'INS_vel_y_can', ...  % FIX: INS_vel hinzugefuegt!
        'ams_overall_voltage_can', 'ams_capacity_fl_can', ...
        'ams_cell_min_voltage_can', 'ams_cell_max_voltage_can', ...
        'ams_cell_avg_temp_can', 'ams_cell_min_temp_can', 'ams_cell_max_temp_can', ...
        'ams_cell_overvoltage_b_can', 'ams_cell_undervoltage_b_can', ...
        'ams_cell_overtemp_b_can', 'ams_cell_undertemp_b_can', ...
        'ams_ok_b_can', 'ams_ok_pst_b_can', 'ams_slave_fail_b_can', ...
        'ams_com_error_can', 'ams_com_error_occu_b_can', ...
        'ams_balance_fb_err_b_can', 'ams_balancing_active_b_can', ...
        'ams_fan_duty_can', 'ams_pecErrors_can', ...
        'ams_overvoltage_occu_b_can', 'ams_undervoltage_occu_b_can', ...
        'ams_overtemp_occu_b_can', 'ams_undertemp_occu_b_can', ...
        'ams_overcurrent_occu_b_can', 'ams_ivtTimeout_occu_b_can', ...
        'IVT_Result_I_can', 'IVT_Result_U1_Pre_Airs_can', 'IVT_Result_U2_Post_Airs_can', ...
        'IVT_Result_U3_can', 'IVT_Result_W_can', ...
        'IVT_Result_I_Channel_Error_b_can', 'IVT_Result_As_Channel_Err_b_can', ...
        'IVT_Result_System_Error_b_can', 'IVT_Result_OCS_b_can', ...
        'IVT_Result_Measurement_Err_b_can', ...
        'air_minus_closed_b_can', 'air_plus_closed_b_can', ...
        'air_minus_aux_b_can', 'air_plus_aux_b_can', ...
        'precharge_closed_b_can', 'precharge_aux_b_can', ...
        'imd_ok_b_can', 'imd_ok_pst_b_can', 'imd_state_can', 'imd_insulation_can', ...
        'tsal_state_can', 'tsal_hv_bat_b_can', 'tsal_error_b_can', ...
        'ts_active_b_can', 'ts_activate_b_can', 'ts_state_can', 'ts_precharge_progress_can', ...
        'unitek_fl_speed_motor_ist_can', 'unitek_fl_torque_motor_ist_can', ...
        'unitek_fl_torque_motor_soll_can', 'unitek_fl_motor_temp_can', ...
        'unitek_fl_igbt_temp_can', 'unitek_fl_Vdc_Bus_can', 'unitek_fl_i_ist_can', ...
        'unitek_fl_status_can', 'unitek_fl_rdy_b_can', 'unitek_fl_rfe_b_can', ...
        'unitek_fl_run_b_can', 'unitek_fl_go_b_can', 'unitek_fl_feedback_b_can', ...
        'unitek_fl_overvoltage_b_can', 'unitek_fl_motortemp_b_can', 'unitek_fl_motortemp_w_b_can', ...
        'unitek_fl_devicetemp_b_can', 'unitek_fl_devicetemp_w_b_can', ...
        'unitek_fl_power_fault_b_can', 'unitek_fl_rfe_fault_b_can', ...
        'unitek_fl_i_peak_b_can', 'unitek_fl_i_lim_inuse_ramp_can', ...
        'unitek_fr_speed_motor_ist_can', 'unitek_fr_torque_motor_ist_can', ...
        'unitek_fr_torque_motor_soll_can', 'unitek_fr_motor_temp_can', ...
        'unitek_fr_igbt_temp_can', 'unitek_fr_Vdc_Bus_can', 'unitek_fr_i_ist_can', ...
        'unitek_fr_status_can', 'unitek_fr_rdy_b_can', 'unitek_fr_rfe_b_can', ...
        'unitek_fr_run_b_can', 'unitek_fr_go_b_can', 'unitek_fr_feedback_b_can', ...
        'unitek_fr_overvoltage_b_can', 'unitek_fr_motortemp_b_can', 'unitek_fr_motortemp_w_b_can', ...
        'unitek_fr_devicetemp_b_can', 'unitek_fr_power_fault_b_can', 'unitek_fr_rfe_fault_b_can', ...
        'unitek_rl_speed_motor_ist_can', 'unitek_rl_torque_motor_ist_can', ...
        'unitek_rl_torque_motor_soll_can', 'unitek_rl_motor_temp_can', ...
        'unitek_rl_igbt_temp_can', 'unitek_rl_Vdc_Bus_can', 'unitek_rl_i_ist_can', ...
        'unitek_rl_status_can', 'unitek_rl_rdy_b_can', 'unitek_rl_rfe_b_can', ...
        'unitek_rl_run_b_can', 'unitek_rl_go_b_can', 'unitek_rl_feedback_b_can', ...
        'unitek_rl_overvoltage_b_can', 'unitek_rl_motortemp_b_can', 'unitek_rl_motortemp_w_b_can', ...
        'unitek_rl_devicetemp_b_can', 'unitek_rl_power_fault_b_can', 'unitek_rl_rfe_fault_b_can', ...
        'unitek_rr_speed_motor_ist_can', 'unitek_rr_torque_motor_ist_can', ...
        'unitek_rr_torque_motor_soll_can', 'unitek_rr_motor_temp_can', ...
        'unitek_rr_igbt_temp_can', 'unitek_rr_Vdc_Bus_can', 'unitek_rr_i_ist_can', ...
        'unitek_rr_status_can', 'unitek_rr_rdy_b_can', 'unitek_rr_rfe_b_can', ...
        'unitek_rr_run_b_can', 'unitek_rr_go_b_can', 'unitek_rr_feedback_b_can', ...
        'unitek_rr_overvoltage_b_can', 'unitek_rr_motortemp_b_can', 'unitek_rr_motortemp_w_b_can', ...
        'unitek_rr_devicetemp_b_can', 'unitek_rr_power_fault_b_can', 'unitek_rr_rfe_fault_b_can', ...
        'drive_pwtrTqTarget_can', 'tq_vehicle_pos_limit_can', 'tq_vehicle_neg_limit_can', ...
        'drive_deratingMotorTemp_b_can', 'drive_deratingAccuTemp_b_can', ...
        'drive_deratingInverterTemp_b_can', 'drive_deratingAccuSoc_b_can', ...
        'drive_deratingMotorCurrent_b_can', 'drive_deratingPeakPerf_b_can', ...
        'drive_stratRecuActive_b_can', 'drive_powerLimitActive_b_can', ...
        'tqv_result_fl_can', 'tqv_result_fr_can', 'tqv_result_rl_can', 'tqv_result_rr_can', ...
        'tqv_rot_spd_fl_can', 'tqv_rot_spd_fr_can', 'tqv_rot_spd_rl_can', 'tqv_rot_spd_rr_can', ...
        'tqv_status_tc_enabled_b_can', 'tqv_status_tqv_enabled_b_can', ...
        'tqv_status_gps_fix_aquired_b_can', 'tqv_status_tqv_strength_can', ...
        'tqv_status_tqv_base_strength_can', 'tqv_status_tc_mu_factor_can', ...
        'tqv_status_tc_slip_target_can', 'tqv_tire_steerangle_can', ...
        'tqv_tqLimitPos_front_can', 'tqv_tqLimitNeg_front_can', ...
        'tqv_tqLimitPos_rear_can', 'tqv_tqLimitNeg_rear_can', ...
        'slip_compare_val_fl_can', 'slip_compare_val_fr_can', ...
        'slip_compare_val_rl_can', 'slip_compare_val_rr_can', ...
        'wpmd_brake_temp_fl_can', 'wpmd_brake_temp_fr_can', ...
        'wpmd_rotor_temp_fl_can', 'wpmd_rotor_temp_fr_can', ...
        'wpmd_trans_temp_fl_can', 'wpmd_trans_temp_fr_can', ...
        'wpmd_brake_temp_e_b_fl_can', 'wpmd_brake_temp_e_b_fr_can', ...
        'wpmd_rotor_temp_e_b_fl_can', 'wpmd_rotor_temp_e_b_fr_can', ...
        'ebs_preasure_front_can', 'ebs_preasure_rear_can', ...
        'ebs_preasure_storage_can', 'ebs_preasure_cyl_front_can', 'ebs_preasure_cyl_back_can', ...
        'SDC_AS_closed_b_can', 'SDC_Latch_Ready_b_can', 'sdc_res_b_can', ...
        'bspd_b_can', 'bspd_avoid_b_can', 'bspd_sensor_err_b_can', ...
        'bots_b_can', 'hv_current_bspd_can', 'hv_current_bspd_High_can', ...
        'lap_cnt_can', 'laptime_can', 'lap_time_last_can', 'lap_time_best_can', ...
        'lap_dist_can', 'lap_trigger_b_can', ...
        'PDU_DCDC_12V_Gen_vout_can', 'PDU_DCDC_12V_Gen_iout_can', 'PDU_DCDC_12V_Gen_temp_can', ...
        'PDU_DCDC_12V_Gen_vin_can', 'PDU_DCDC_12V_Gen_e_b_can', 'PDU_DCDC_12V_Gen_e_occu_b_can', ...
        'PDU_DCDC_24V_Gen_vout_can', 'PDU_DCDC_24V_Gen_iout_can', 'PDU_DCDC_24V_Gen_temp_can', ...
        'PDU_DCDC_24V_Gen_vin_can', 'PDU_DCDC_24V_Gen_e_b_can', 'PDU_DCDC_24V_Gen_e_occu_b_can', ...
        'PDU_DCDC_DV_vout_can', 'PDU_DCDC_DV_iout_can', 'PDU_DCDC_DV_temp_can', ...
        'PDU_DCDC_DV_vin_can', 'PDU_DCDC_DV_e_b_can', 'PDU_DCDC_DV_e_occu_b_can', ...
        'PDU_DCDC_Ewp_Mot_1_vout_can', 'PDU_DCDC_Ewp_Mot_1_iout_can', 'PDU_DCDC_Ewp_Mot_1_temp_can', ...
        'PDU_DCDC_Ewp_Mot_1_e_b_can', 'PDU_DCDC_Ewp_Mot_1_e_occu_b_can', ...
        'PDU_DCDC_Ewp_Mot_2_vout_can', 'PDU_DCDC_Ewp_Mot_2_iout_can', 'PDU_DCDC_Ewp_Mot_2_temp_can', ...
        'PDU_DCDC_Ewp_Mot_2_e_b_can', 'PDU_DCDC_Ewp_Mot_2_e_occu_b_can', ...
        'PDU_DCDC_Fan_Inv_vout_can', 'PDU_DCDC_Fan_Inv_iout_can', 'PDU_DCDC_Fan_Inv_temp_can', ...
        'PDU_DCDC_Fan_Inv_e_b_can', 'PDU_DCDC_Fan_Inv_e_occu_b_can', ...
        'PDU_DCDC_Fan_Motor_vout_can', 'PDU_DCDC_Fan_Motor_iout_can', 'PDU_DCDC_Fan_Motor_temp_can', ...
        'PDU_DCDC_Fan_Motor_e_b_can', 'PDU_DCDC_Fan_Motor_e_occu_b_can', ...
        'PDU_eFuse_ACE_IMON_can', 'PDU_eFuse_ACE_e_b_can', 'PDU_eFuse_ACE_IMON_e_b_can', ...
        'PDU_eFuse_AMS_IMON_can', 'PDU_eFuse_AMS_e_b_can', 'PDU_eFuse_AMS_IMON_e_b_can', ...
        'PDU_eFuse_AMS_Fans_IMON_can', 'PDU_eFuse_AMS_Fans_e_b_can', ...
        'PDU_eFuse_DVSC_IMON_can', 'PDU_eFuse_DVSC_e_b_can', 'PDU_eFuse_DVSC_IMON_e_b_can', ...
        'PDU_eFuse_Ewp_Inv_IMON_can', 'PDU_eFuse_Ewp_Inv_e_b_can', ...
        'PDU_eFuse_Inv_FL_IMON_can', 'PDU_eFuse_Inv_FL_e_b_can', 'PDU_eFuse_Inv_FL_IMON_e_b_can', ...
        'PDU_eFuse_Inv_FR_IMON_can', 'PDU_eFuse_Inv_FR_e_b_can', 'PDU_eFuse_Inv_FR_IMON_e_b_can', ...
        'PDU_eFuse_Inv_RL_IMON_can', 'PDU_eFuse_Inv_RL_e_b_can', 'PDU_eFuse_Inv_RL_IMON_e_b_can', ...
        'PDU_eFuse_Inv_RR_IMON_can', 'PDU_eFuse_Inv_RR_e_b_can', 'PDU_eFuse_Inv_RR_IMON_e_b_can', ...
        'PDU_eFuse_SDC_IMON_can', 'PDU_eFuse_SDC_e_b_can', 'PDU_eFuse_SDC_IMON_e_b_can', ...
        'PDU_eFuse_12V_Gen_IMON_can', 'PDU_eFuse_12V_Gen_e_b_can', 'PDU_eFuse_12V_Gen_IMON_e_b_can', ...
        'ewpInverterDuty_can', 'ewpMotorDuty_can', 'fanInverterDuty_can', 'fanMotorDuty_can', ...
        'PDU_DCDC_Inv_temp_can', 'PDU_DCDC_Inv_temp_e_b_can', ...
        'DL_EBS_state_can', 'DL_AS_state_can', 'DL_speed_actual_can', 'DL_speed_target_can', ...
        'DL_steering_angle_actual_can', 'DL_steering_angle_target_can', ...
        'DL_Motor_moment_actual_can', 'DL_Motor_moment_target_can', ...
        'DL_Brake_hydr_actual_can', 'DL_Brake_hydr_target_can', ...
        'DL_Cones_count_actual_can', 'DL_Cones_count_all_can', ...
        'DL_Lap_counter_can', 'DL_Yaw_rate_can', ...
        'VCU_Statemachine_can', 'VCU_AMI_state_can', 'VCU_GO_b_can', ...
        'VCU_sc_b_can', 'ts_activate_b_can', ...
    };

    for i = 1:cfg.ams.anzahl_zellen
        signale_liste{end + 1} = sprintf('ams_cell_voltage%03d_can', i);
    end
    for i = 1:cfg.ams.anzahl_temp_sensoren
        signale_liste{end + 1} = sprintf('ams_cell_temp%03d_can', i);
    end
end